configform_example_form:
  path: '/examples/configform_example/form'
  defaults:
    _form: '\Drupal\configform_example\Form\ConfigFormExampleConfigForm'
    _title: 'Config Demo Form'
  requirements:
    _permission: 'access simple page'
